### ISSUE TITLE
feat: Integration with the API credentials login endpoint

### ISSUE THREAD

**Issue by angel-penchev** [KokosTech/lenslend-frontend#5]
**Issue type**
I'm submitting a ...

- [ ] 🐛 bug report
- [x] 🆕 feature request
- [ ] 🧪 testing request
- [ ] 📄 documentation request
- [ ] 📦 CI/CD request
- [ ] ❓ question

**Describe the feature you'd like added**
- Set up NextAuth in `sugaming-site` to use the new authentication endpoint.
- Create a basic credentials login screen.

**Additional context**
Resources:
- [Credentials Provider | NextAuth](https://next-auth.js.org/v3/configuration/providers#credentials-provider) - NextAuth documentation

This issue is depends on KokosTech/lenslend-backend#5.

**Comment by KokosTech** [comment]
finished with #44
